# Generated by Django 4.2.16 on 2024-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
